# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: course.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lecture_pb2 as lecture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x1a\rlecture.proto\"\x87\x01\n\x06\x43ourse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x03(\t\x12%\n\x07lecture\x18\x03 \x03(\x0b\x32\x14.Course.LectureEntry\x1a\x38\n\x0cLectureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Lecture:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COURSE_LECTUREENTRY']._options = None
  _globals['_COURSE_LECTUREENTRY']._serialized_options = b'8\001'
  _globals['_COURSE']._serialized_start=32
  _globals['_COURSE']._serialized_end=167
  _globals['_COURSE_LECTUREENTRY']._serialized_start=111
  _globals['_COURSE_LECTUREENTRY']._serialized_end=167
# @@protoc_insertion_point(module_scope)
