# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\"Z\n\x05Video\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.Video.Type\x12\x0b\n\x03url\x18\x02 \x01(\t\")\n\x04Type\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03MP4\x10\x01\x12\x07\n\x03MOV\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEO']._serialized_start=15
  _globals['_VIDEO']._serialized_end=105
  _globals['_VIDEO_TYPE']._serialized_start=64
  _globals['_VIDEO_TYPE']._serialized_end=105
# @@protoc_insertion_point(module_scope)
